### ISSUE TITLE
New created columns inside @mutate is not immediately available within the call

### ISSUE THREAD

**Issue by yanwenwang24** [TidierOrg/TidierData.jl#121]
Suppose the `df` does not have column `x1` initially.

```
@chain df begin
    @mutate(
        x1 = 1,
        x2 = x1 + 1
    )
end
```

This works in `dplyr` but does work in `TidierData`. I wonder if it is possible to call the newly created column with the same call? Many thanks.

**Comment by drizk1** [comment]
This is not yet supported due to how the underlying Dataframes.jl `transform` function behaves. 

A more in depth discussion is [available here ](https://discourse.julialang.org/t/simple-transformation-of-a-dataframe-with-grouped-data/115660/3)
