### ISSUE TITLE
`@filter ` will not interpolate column name

### ISSUE THREAD

**Issue by co1emi11er2** [TidierOrg/TidierData.jl#123]
The following does not work:

```julia
t = :bar
s = "foo"
@chain df begin
    @filter(!!t == !!s)
end
```

This works though:
```julia
s = "foo"
@chain df begin
    @filter(bar == !!s)
end
```

**Comment by drizk1** [comment]
Although the documentation is not yet updated, TidierData is shifting to use the following method of interpolation that leverages `@eval` and `$` 

Demarcate the variables with `$` and start the chain with `@eval`

```
t = :bar
s = "foo"
@eval @chain df begin
    @filter($t == $s)
end
```
This should work already without needing to update the package.

**Comment by kdpsingh** [comment]
We have documented the new preferred interpolation syntax here: https://tidierorg.github.io/TidierData.jl/latest/examples/generated/UserGuide/interpolation/

Closing this issue.
