### ISSUE TITLE
Improvement to interpolation - making it deferred

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/TidierData.jl#16]
Right now, interpolation occurs eagerly inside the `parse_interpolation()` function, which is evaluated before the quoted return expression is formed.

If we can move all the parsing functions into the body of the quoted expression, which should be possible to do by inserting a `QuoteNode()` around the provided user expressions, then the interpolation can be deferred. The primary advantage of this is that the interpolation will occur at runtime rather than at parse time, which means that it will work out-of-the-box within for-loops.

The limitation that the interpolated variable must be within the global scope will still exist, but I don't think that is solvable because the solution described here for accessing the local scope within macros (https://stackoverflow.com/questions/21267962/how-can-i-eval-a-local-variable-in-julia) won't work within Tidier.

Here's an example (as a note to self) of how deferred evaluation works (where the `Main.eval()` is wrapped inside the quoted expression within the macro). This is how we will plan to implement `!!` interpolation in TidierData moving forward.

```julia
a = :b
b = 10

macro test(obj)
expr = quote
  println($obj)
  println(Main.eval($obj))
  # $obj -> Main.eval($obj)
end

expr
end

@test(a)
```

**Comment by vchuravy** [comment]
The normal way of accessing a local variable is to use `esc` on the user provided value.

So if you delay the interpolation (and thus not use eval) and then use `esc` `!!` should just be able to access the scope local variable.

**Comment by kdpsingh** [comment]
Thanks for doing this. Escaping it was actually what I was planning to do -- just needed to make sure that it didn't mess up any of the other parsing functions.

Your PR is much, much appreciated!

Will see if it passes checks and will play with it a bit. Really looking forward to implementing this!

**Comment by kdpsingh** [comment]
(I already escape functions to ensure that user-defined functions are available within the macros but hadn't implemented escaping here because I was running into issues with how anonymous functions are named/generated.)
