### ISSUE TITLE
Need to implement slice_head(), slice_tail() - Done with slice_min(), slice_max(), and slice_sample()

### ISSUE THREAD

**Issue by PursuitOfDataScience** [TidierOrg/TidierData.jl#4]
Hi,

As an experienced tidyverse user/developer who is learning Julia, I am just impressed by the Tidier package. Transferring my R knowledge to Julia is almost effortless, thanks to Tidier! 

There are two very useful functions from dplyr: slice_min() and slice_max(). I think they should be included in Tidier. This [link](https://dplyr.tidyverse.org/reference/slice.html) leads to the R documentation. 

Thanks!

**Comment by kdpsingh** [comment]
Per https://x.com/alextantos1/status/1692440814448759208?s=46&t=PEX2NKcgCDoTOe3kHQFmDA, we should also add `@slice_sample()`

**Comment by kdpsingh** [comment]
`@slice_sample()` is now implemented. Still need to implemented the other `@slice_*` variants.

**Comment by drizk1** [comment]
Finally figured out '@slice_min' and '@slice_max' and PRed them

**Comment by kdpsingh** [comment]
Merged! Thank you so much @drizk1.

We’re only missing `@slice_head()` and `@slice_tail()` so will leave this issue open but will rename it.

**Comment by drizk1** [comment]
Awesome. I'll take a look at those.

**Comment by kdpsingh** [comment]
Thanks to @drizk1, `@slice_head()` and `@slice_tail()` are now implemented in v0.13.1. Will be pushed to registry shortly.
