### ISSUE TITLE
@clean_names does not remove slash symbol

### ISSUE THREAD

**Issue by ymer** [TidierOrg/TidierData.jl#52]
Tidyverse:

```
library(tidyverse)
library(janitor) 
df = tibble("A/B" = c(1,2)) 
clean_names(df)
```

Output: A single column called "a_b"

Tidier:
```
df = DataFrame("A/B" => [1, 2])
@clean_names(df)
```

Output: A column called "a/_b"

**Comment by kdpsingh** [comment]
This should now be fixed as per https://github.com/TheRoniOne/Cleaner.jl/issues/9
