### ISSUE TITLE
How can I change the  data type of a column?

### ISSUE THREAD

**Issue by ymer** [TidierOrg/TidierData.jl#53]
In Tidyverse I can change the type of a column using this command:

`col_name = as.integer(col_name)`

What is the Tidier equivalent?

This works in Julia

`df.plus65 = parse.(Int, df.plus65)`

But this does not work in Tidier:

`@mutate(df, plus65 = parse.(Int, plus65))`

(Neither without the broadcast.)

**Comment by kdpsingh** [comment]
In Tidier you can do:

```
col_name = as_integer.(col_name)
```

This can also be used inside of Tidier macros as follows:

```
@mutate(df, col_name = as_integer(col_name))
```

The reason `parse()` doesn't work here is that we haven't programmed in data types into Tidier yet, so it looks for a column named `Int`. The following should work.

```
@mutate(df, plus65 = parse.(!!Int, plus65))
```

The `!!` ("bang bang") interpolation is a way to access named variables defined outside of the data frame. There is an open issue on this, and we are plannng to fix it so this is not needed.

**Comment by kdpsingh** [comment]
I'll close this issue for now. Feel free to re-open if needed.
