### ISSUE TITLE
Filtering out missing values with @filter

### ISSUE THREAD

**Issue by ovancantfort** [TidierOrg/TidierData.jl#60]
Hello,
Thanks for this wonderful package!
I was wondering if there is a way to filter out the missing values in a specific column using @filter

I tried
@filter(df, !ismissing(Column_name)) but it fails with the following error

_ArgumentError: function passed to `subset`/`subset!` returned value of type `Tuple{BitVector, BitVector}` while it must return an AbstractVector` when subsetting a data frame_

I also tried
@filter(df, Column_name!=missing) but is fails because it interprets the word 'missing' as a column name (same issue as #38 )

Not urgent as I can use dropmissing in the chain, but it would be cleaner to have all filters together in @filter.

Thanks a lot

**Comment by kdpsingh** [comment]
The code you provided should work, assuming that `Column_name` is the actual name of the column.

For example, this works for me. Can you confirm if this works on your end? Or provide an example that is giving you an error?

Thanks!

```julia
df = DataFrame(a = [1,2,3,4,missing])
@filter(df, !ismissing(a))
```

```
4×1 DataFrame
 Row │ a      
     │ Int64? 
─────┼────────
   1 │      1
   2 │      2
   3 │      3
   4 │      4
```
