### ISSUE TITLE
@drop_missing() stopped working in 1.10.0

### ISSUE THREAD

**Issue by awojtas-r** [TidierOrg/TidierData.jl#78]
After moving from Julia ver. 1.8.5 to 1.10 drop_missing() function stopped working regardless of providing columns, producing LoadError: UndefVarError: `@drop_missing` not defined

**Comment by kdpsingh** [comment]
Can you go to the package console by pressing `]`, type in `status`, and share the output display the versions of packages you have installed?

**Comment by kdpsingh** [comment]
This in an old version of TidierData.jl prior to the implementation of `@drop_missing()`, which was added in 0.11.0.

To install the latest version, type in `]` to access the package manager and then type `update TidierData`. That should give you access to `@drop_missing()`.

**Comment by awojtas-r** [comment]
> To install the latest version, type in `]` to access the package manager and then type `update TidierData`. That should give you access to `@drop_missing()`.

After trying to update I get no changes and still the same version 0.10. I tried all possible options with reinstalling but still the same. After trying add TidierData#main I got errors with Unsatisfiable requirements, so still no solution for that

**Comment by awojtas-r** [comment]
I tried to update both but it's still the same output

**Comment by kdpsingh** [comment]
Can you remove the Tidier package altogether and then try to update TidierData?

That should fix it. Appreciate the patience, and hope it works. I'll add a note to the README if this works.

**Comment by kdpsingh** [comment]
This all stems from a dependency versioning issue in an older version of Tidier that has since been fixed.

**Comment by awojtas-r** [comment]
> Can you remove the Tidier package altogether and then try to update TidierData?


I removed Tidier and tried to update TidierData, unfortunately nothing changed and still 0.10

**Comment by kdpsingh** [comment]
Try `import Pkg; Pkg.gc()` and then try to upgrade TidierData.

I wonder if despite your removing Tidier, it is still somehow cached. If that doesn't work, I'll tag some other folks who may know more.

**Comment by kdpsingh** [comment]
I'm going to close this issue for now as it's a general package management issue. If you still need help, please feel free to reply to this.
