### ISSUE TITLE
@clean_names has a little problem with abbreviation feature name

### ISSUE THREAD

**Issue by math4mad** [TidierOrg/TidierData.jl#79]
If feature  is abbr.  then will add `_ `, like  id => `i_d`, bmi=>`b_m_i`

[Diabetes Dataset](https://www.kaggle.com/datasets/akshaydattatraykhare/diabetes-dataset)

![screenshot_1761](https://github.com/TidierOrg/TidierData.jl/assets/113895984/2e3cfac1-b113-47b9-9872-900a9b2cc5f6)

**Comment by kdpsingh** [comment]
For the `@clean_names()` package, we actually wrap the `polish_names()` function from Cleaner.jl.

I would suggest opening an issue there: https://github.com/TheRoniOne/Cleaner.jl

You're right that when janitor sees multiple consecutive capital letters, it doesn't add underscores to separate them.

I'll leave this issue open on our end so we can track this. Thank you!

**Comment by kdpsingh** [comment]
This is now fixed thanks to a fix to Cleaner.jl (Thanks @TheRoniOne!)
