### ISSUE TITLE
Here is an interesting topic about  document 

### ISSUE THREAD

**Issue by math4mad** [TidierOrg/TidierData.jl#95]
[Building a RAG Chatbot over DataFrames.jl Documentation - Hands-on Guide](https://forem.julialang.org/svilupp/building-a-rag-chatbot-over-dataframesjl-documentation-hands-on-guide-449m)

**Comment by kdpsingh** [comment]
Thanks for sharing this. Going to close this issue since there is nothing we need to build for now.
