### ISSUE TITLE
how to create  Discrete Joint Distributions   table with tidierdata.jl?

### ISSUE THREAD

**Issue by math4mad** [TidierOrg/TidierData.jl#96]
how to create  Discrete Joint Distributions   table with tidierdata.jl?

could any one  give a example

**Comment by kdpsingh** [comment]
Can you example of what you want to create using something other than TidierData?

If so, would be happy to help recreate it with TidierData.

**Comment by kdpsingh** [comment]
Will close for now. Happy to re-open if you can share an example.
